/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.novatronic.frame;

import com.novatronic.bean.ListaBanco;
import com.novatronic.controller.GeneradorScripts;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author amartinez
 */
public class PrincipalFrame extends javax.swing.JFrame implements ActionListener{

    
    String rutaExcel;
    
    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
        
        seleccionarExcelButton.addActionListener(this);
        generarScriptButton.addActionListener(this);
        
        setSize(600,300);
        setLocation(400,200);
        setResizable(false);
    }

    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codAdqTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codProcTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codAutTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codLisIniTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fecIniTextField = new javax.swing.JTextField();
        fecTermTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        indEstTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        seleccionarExcelButton = new javax.swing.JButton();
        generarScriptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código Adquiriente");

        codAdqTextField.setText("999978");

        jLabel2.setText("Código Procesador");

        codProcTextField.setText("000001");

        jLabel3.setText("Código Autorizador");

        codAutTextField.setText("900002");

        jLabel4.setText("Código de lista inicial");

        codLisIniTextField.setText("010050");

        jLabel5.setText("Fecha de Inicio");

        jLabel6.setText("Fecha de Término");

        fecIniTextField.setText("01/01/2018");

        fecTermTextField.setText("01/01/2024");

        jLabel7.setText("índice de estado");

        indEstTextField.setText("1");

        jLabel8.setText("Archivo excel");

        seleccionarExcelButton.setText("Seleccionar");
        seleccionarExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarExcelButtonActionPerformed(evt);
            }
        });

        generarScriptButton.setText("Generar script");
        generarScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarScriptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codAdqTextField)
                            .addComponent(codProcTextField)
                            .addComponent(codAutTextField)
                            .addComponent(codLisIniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seleccionarExcelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fecTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fecIniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(indEstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(generarScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codAdqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(indEstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fecIniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fecTermTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(seleccionarExcelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(codProcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(codAutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(codLisIniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(generarScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     public void actionPerformed(ActionEvent e) {
        if(e.getSource()==seleccionarExcelButton){
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(this);
            
            File excel = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(null, excel.getAbsolutePath());
            rutaExcel = excel.getAbsolutePath();
            
        }
        
        if(e.getSource()==generarScriptButton){
             //Variables que reciben los valores ingresados por el usuario
            String codigoAdquiriente = codAdqTextField.getText();
            String codigoProcesador = codProcTextField.getText();
            String codigoAutorizador = codAutTextField.getText();
            String codigoLista = codLisIniTextField.getText();
            String strFecIni = fecIniTextField.getText();
            String indiceEstado = indEstTextField.getText();
            String strFechaTermino = fecTermTextField.getText();
            
            JOptionPane.showMessageDialog( null, codigoAdquiriente+" , "+ codigoProcesador + " , "+codigoAutorizador+" , "+codigoLista+" , "+strFecIni+" , "+strFechaTermino);
            
            ListaBanco listaBanco = new ListaBanco(codigoAdquiriente, codigoProcesador,
                                        codigoAutorizador, codigoLista, strFecIni,
                                        indiceEstado);
            
            new GeneradorScripts().generarScript( listaBanco , strFechaTermino, rutaExcel);
        }
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void seleccionarExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarExcelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarExcelButtonActionPerformed

    private void generarScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarScriptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generarScriptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codAdqTextField;
    private javax.swing.JTextField codAutTextField;
    private javax.swing.JTextField codLisIniTextField;
    private javax.swing.JTextField codProcTextField;
    private javax.swing.JTextField fecIniTextField;
    private javax.swing.JTextField fecTermTextField;
    private javax.swing.JButton generarScriptButton;
    private javax.swing.JTextField indEstTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton seleccionarExcelButton;
    // End of variables declaration//GEN-END:variables

   
}
